services:
    alexandret.seodescription.listener:
        class: alexandret\seodescription\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
